### ISSUE TITLE
chore(toplingdb): publish traceable JNI Maven artifacts

### ISSUE THREAD

**Issue by imbajin** [hugegraph/hugegraph#213]
## Context

hugegraph/hugegraph#179 currently consumes a checked-in Topling JNI JAR:

```text
cn.topling:rocksdbjni:8.10.2-20260725.141011-1
sha256: 86eb1bd3d9f84ef0dddd3fe95c640a6f145ca2d5a26a5ba628f1f298a2031fae
```

The current [Topling JNI workflow](https://github.com/hugegraph/toplingdb/actions/workflows/topling-jni.yml) builds on Ubuntu 24.04 with GCC 13 and publishes `cn.topling:rocksdbjni` to the `hugegraph/toplingdb` GitHub Packages registry. It does not upload a normal Actions artifact, and this is not yet a release-grade Maven distribution path for HugeGraph users and ASF packaging.

This is not a functional blocker for the core Easy Migrate integration in PR #179. It is a release-readiness item that must be resolved before an official HugeGraph release includes ToplingDB.

## Required outcome

- Publish under an agreed Topling Maven organization/group and stable artifact ID.
- Define an immutable version-to-source-commit mapping.
- Record the exact ToplingDB and rockside commits, submodules, toolchain, build flags, and target CPU baseline.
- Publish POM/module metadata, checksums, signatures, LICENSE/NOTICE, and preferably SBOM/provenance attestations.
- Choose and document the applicable upstream license option for the exact binary.
- Make the artifact available to HugeGraph builds without checking compiled binaries into the source release.
- Define snapshot and release repository access for CI, developers, and end users.
- Add a consumer-side verification that resolves the coordinate and checks the expected native ELF and checksum/provenance.

## Compatibility metadata to retain

The currently validated JNI ELF requires at least:

```text
GLIBC_2.38
GLIBCXX_3.4.32
CXXABI_1.3.13
```

It also contains `-march=haswell`, `-mbmi`, and `-mbmi2`, so the supported x86_64 CPU baseline must be explicit.

Related: hugegraph/hugegraph#179 and https://github.com/hugegraph/toplingdb/actions/workflows/topling-jni.yml.

**Comment by imbajin** [comment]
## 2026-08-31 provenance investigation

I re-checked the live producer rather than relying on the earlier PR snapshot.

Current observations:

- `hugegraph/toplingdb` defaults to `memtable_as_log_index`; current head is `79949b8ecda10bb3d65bc1e07bece2777fa1e4df`.
- The Maven package currently exposes only `cn.topling:rocksdbjni:8.10.2-SNAPSHOT` (updated 2026-07-25).
- `topling-jni.yml` uses Ubuntu 24.04, GCC/G++ 13, Temurin JDK 11, shallow checkout, recursive submodules, and `deploy:deploy-file` to GitHub Packages.
- The workflow does not record the resolved submodule/SidePlugin commits, compiler/binutils versions, effective flags, CPU baseline, native ABI requirements, or an immutable version-to-source mapping.
- It does not publish a normal Actions artifact containing checksums and build metadata, nor signatures, SBOM, or provenance attestation.
- The existing HugeGraph consumer therefore remains a timestamped snapshot plus a separately recorded SHA-256/ABI contract; that is enough for the current functional candidate but not an official release path.

A bounded first producer-side milestone can be implemented without choosing the final Maven release policy:

```text
checkout exact commit + submodules
        ↓
build JNI once
        ↓
consumer smoke + ldd/readelf/CPU-baseline checks
        ↓
rocksdbjni.jar + SHA256SUMS + provenance.json + dependency manifest
        ↓
immutable Actions artifact + attestation
```

`provenance.json` should include the ToplingDB commit, every submodule and SidePlugin commit, workflow run/ref, JDK/GCC/binutils/glibc versions, effective make flags, `readelf` ABI/ISA evidence, artifact coordinate, and SHA-256. The Maven release milestone then separately needs the agreed group/artifact/version policy, license choice, release repository, signatures, LICENSE/NOTICE, and consumer access contract.

This confirms #213 remains non-blocking for hugegraph/hugegraph#179 but is still required before an official release can replace the checked-in binary path. No release artifact or stable coordinate is claimed by this update.
